# Generated by Django 3.0.7 on 2020-06-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine_hw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('id_machine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='data_hg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_1', models.IntegerField()),
                ('humid_1', models.IntegerField()),
                ('sw_1', models.IntegerField()),
                ('sw_2', models.IntegerField()),
                ('time_data', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='dashboard.machine_hw')),
            ],
        ),
    ]
