# Generated by Django 3.0.7 on 2020-06-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_hg_outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bomba_1', models.BooleanField()),
                ('Bomba_2', models.BooleanField()),
                ('Bomba_3', models.BooleanField()),
                ('Llum', models.BooleanField()),
                ('Bomba_h20', models.BooleanField()),
                ('Ventilador', models.BooleanField()),
                ('Altura', models.IntegerField()),
                ('time_data', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_output', to='dashboard.machine_hw')),
            ],
        ),
    ]
