# Generated by Django 3.0.7 on 2020-07-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_hg_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_hg_confgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Light_time', models.IntegerField()),
                ('Light_on', models.IntegerField()),
                ('H20_duty', models.IntegerField()),
                ('Max_temp', models.IntegerField()),
                ('Fan_Duty', models.IntegerField()),
                ('time_data', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_config', to='dashboard.machine_hw')),
            ],
        ),
    ]
