# Generated by Django 2.2.5 on 2020-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_data_hg_confgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_hg',
            name='humid_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_hg',
            name='temp_1',
            field=models.FloatField(),
        ),
    ]
